# NumPy

In [1]:
import numpy as np

## Array

In [2]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
print(a[0])
a[0]

[1 2 3 4]


array([1, 2, 3, 4])

In [10]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[1,2]

7

In [12]:
# Mengetahui dimensional array
a.ndim

2

In [13]:
# Mengetahui bentuk array
a.shape

(3, 4)

### Creating Array

In [14]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [15]:
np.zeros(6) # (6, )

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((6,2)) # (6, 2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
form1 = ((4, 5))
np.zeros(form1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
ones1 = np.ones((6,2) ) #(6,2)
print(ones1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
form1 = ((4, 5))
ones2 = np.ones(form1)
print(ones2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
ones3 = np.ones((2, 3, 2))
ones3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [22]:
numbers = np.full((2 ,4), 7)
numbers

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [24]:
float_numbers = np.full((2 ,4), 7, dtype='float')
float_numbers

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [25]:
empty_array = np.empty(6)
empty_array

array([0., 0., 0., 0., 0., 0.])

In [26]:
# Array with range
# Slicing :: Start is Inclusive Stop is Exclusive
print(np.arange(4)) # start default = 0, step default = +1
print(np.arange(0, 10, 2)) # start, stop, step

[0 1 2 3]
[0 2 4 6 8]


In [29]:
# Hanya menampilkan angka genap
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# Hanya menampilkan angka ganjil
np.arange(0, 20, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
# Jika negatif
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [34]:
# Contoh lain
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

### Add, Remove, and Sort

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr
# np.append(arr, [1,2] )

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr_new = np.append(arr, [1,2] )
arr_new

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [42]:
arr_new.shape

(10,)

In [43]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.delete(arr, 6)

array([1, 2, 3, 4, 5, 6, 8])

In [45]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [46]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
arr2d = np.array([[9, 18, 3, 7], [2, 1, 10, 34], [51, 0, 8, 13]])
arr2d

array([[ 9, 18,  3,  7],
       [ 2,  1, 10, 34],
       [51,  0,  8, 13]])

In [50]:
np.sort(arr2d, axis=0)

array([[ 2,  0,  3,  7],
       [ 9,  1,  8, 13],
       [51, 18, 10, 34]])

In [51]:
np.sort(arr2d, axis=1)

array([[ 3,  7,  9, 18],
       [ 1,  2, 10, 34],
       [ 0,  8, 13, 51]])

### Shape and Size

In [52]:
arr2d.ndim

2

In [53]:
arr2d.shape

(3, 4)

In [54]:
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]], [[0, 1, 2, 3], [4, 5, 6, 7]], [[0, 1, 2, 3], [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [55]:
array_example.ndim

3

In [57]:
array_example.shape

(3, 2, 4)

In [56]:
# Dari perkalian 3 x 2 x 4
array_example.size

24

In [58]:
array_example.dtype

dtype('int32')

In [59]:
# itemsize itu berasal dari int32, dimana 32 dibagi 8 jadi 4
array_example.itemsize
# 00000000 00000000 00000000 00000000    <-- int32
# 7
# 1110
# 00000000 00000000 00000000 00000000
#                                1110

4

In [62]:
# array_example.astype('int16')
array_example = np.array([[[0, 1, 2, 3],
                        [4, 5, 6, 7]],

                        [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                    
                        [[0, 1, 2, 3],
                            [4, 5, 6, 7]]
                        ], dtype = 'int16')
array_example.dtype

dtype('int16')

In [63]:
array_example.itemsize
# 00000000 00000000 <-- int16

2

In [64]:
array_example.nbytes

48

### Reshape

In [66]:
ones3 = np.ones((3, 4))
ones3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
ones3.shape

(3, 4)

In [68]:
# Reshape bisa dilakukan dalam bentuk apapun kecuali kurang atau lebih dari element array yang tertera sebelumnya
ones3.reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
ones3.reshape(1, 12)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [78]:
a = np.arange(6)
c = a.reshape(2, 3, 1)
c

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [74]:
a = np.arange(18)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [75]:
# row-wise operations  ← order=c
# column-wise operations ← order=f

d = a.reshape(3, 3, 2)
print(d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [80]:
np.reshape(d, (9,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

### Convert 1D to 2D

In [81]:
a = np.array([1 ,2 ,3, 4, 5, 6])
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


In [82]:
# np.newaxis to added new axis to array

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [83]:
# Using row vector to convert 1D array to a row vector
# ":" untuk mengambil semua element
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [85]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [86]:
# Penggunaan expand_dims to add an axis at index position
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [87]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and Slicing

In [88]:
data = np.array([1, 2, 3])

print(data)         # 1, 2, 3
print(data[0])      # 1
print(data[1])      # 2
print(data[0:2])     
# [0] [1]       # 1, 2
print(data[1:])
# [1] [2]       # 2, 3
print(data[-2:])
# [-2] [-1]     # 2, 3

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [92]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
# Easily way to print all of values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [94]:
# Perintah memilih angka yang sama dengan atau lebih besar dari 5
five_up = (a>=5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [91]:
# You can select elements that are divisible by 2

divisible_by_2 = (a%2 == 0)
print(a[divisible_by_2])

divisible_by_3= (a%3 == 0)
print(a[divisible_by_3])

[ 2  4  6  8 10 12]
[ 3  6  9 12]


In [95]:
# Bisa menggunakan two conditions using & and | operators
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [90]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

multiple_conditions = ((a > 2) & (a < 11))
a[multiple_conditions]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
random_af = np.random.rand(3,5)
print(random_af)
print(random_af.dtype)



random_af = np.random.rand(5, 1)
print(random_af)

random_af = np.random.rand(3)
print(random_af)

[[0.9648239  0.24095582 0.15539877 0.82882703 0.19657983]
 [0.92766016 0.29300471 0.81090201 0.8621195  0.76853504]
 [0.41270187 0.10465985 0.34695828 0.0413346  0.30164116]]
float64
[[0.65865354]
 [0.70059122]
 [0.15781614]
 [0.61353199]
 [0.31072532]]
[0.66079215 0.74696299 0.05240817]


### Creating Array from Existing Data

In [ ]:
''''''''' Syntax
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()
''''''

In [99]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [101]:
# vstak untuk menumpuk array secara vertikal
a_1 = np.array([[1, 1], [2, 2]])
a_2 = np.array([[3, 3], [4, 4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [102]:
np.vstack((a_1, a_2, a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2]])

In [103]:
np.vstack((a_1, a_2, a_1, a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2],
       [1, 1],
       [2, 2]])

In [106]:
# hstak untuk menumpuk array secara horizontal
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [107]:
np.hstack((a_1, a_2, a_1))

array([[1, 1, 3, 3, 1, 1],
       [2, 2, 4, 4, 2, 2]])

In [108]:
a_3 = np.array([[3, 3, 3],
                [4, 4, 4]])
np.hstack((a_1, a_2, a_1, a_3))

array([[1, 1, 3, 3, 1, 1, 3, 3, 3],
       [2, 2, 4, 4, 2, 2, 4, 4, 4]])

In [109]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [113]:
# If want to split this array into three equally shaped arrays
result = np.hsplit(arrsplit, 3)
result[0]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [114]:
result[1]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [115]:
result[2]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [111]:
# Metode view untuk membuat objek array baru yang terlihat = array asli (shallow copy)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
# Create a new array object that looks at the same data
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

In [ ]:
'''
Addition
subtraction
multiplication
division
and more
'''